const KEY="meknesAdminProducts", OKEY="meknesOrders", SKEY="meknesSettings", SEO="meknesSEO";
const defaultProducts=[
{id:1,name:"زيتون مكناسي مرقد",fr:"Olives de Meknès",cat:"olives",price:35,unit:"500g",stock:40,img:"https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=85",desc:"زيتون مختار بنكهة مغربية أصيلة."},
{id:2,name:"زيت الزيتون",fr:"Huile d’olive",cat:"oil",price:85,unit:"1L",stock:25,img:"https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=85",desc:"زيت زيتون من مصدر واضح، حسب التوفر."},
{id:3,name:"فلفل حار مرقد",fr:"Piments forts marinés",cat:"pepper",price:28,unit:"350g",stock:30,img:"https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=900&q=85",desc:"لمسة حارة لعشاق المائدة المغربية."},
{id:4,name:"مخمرات مغربية",fr:"Préparations traditionnelles",cat:"traditional",price:32,unit:"500g",stock:18,img:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85",desc:"منتوج تقليدي بطابع مغربي."}
];
let products=JSON.parse(localStorage.getItem(KEY)||"null")||defaultProducts;
let orders=JSON.parse(localStorage.getItem(OKEY)||"[]");
let settings=JSON.parse(localStorage.getItem(SKEY)||"{}");
function saveAll(){localStorage.setItem(KEY,JSON.stringify(products));localStorage.setItem(OKEY,JSON.stringify(orders));}
function login(){if(document.getElementById("pin").value==="1234"){localStorage.setItem("adminLogged","1");start()}else alert("رمز الدخول غير صحيح")}
function logout(){localStorage.removeItem("adminLogged");location.reload()}
function start(){document.getElementById("login").style.display="none";document.getElementById("app").style.display="block";renderAll()}
if(localStorage.getItem("adminLogged")==="1")start();
document.querySelectorAll(".side nav button").forEach(b=>b.onclick=()=>showView(b.dataset.view));
function showView(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById(id).classList.add("active");document.querySelectorAll(".side nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===id));document.getElementById("viewTitle").textContent=document.querySelector(`[data-view="${id}"]`).textContent.replace(/[📊🫒📦👥✍️⚙️]/g,"").trim();renderAll()}
function toggleSide(){document.querySelector(".side").classList.toggle("open")}
function renderAll(){renderStats();renderProducts();renderOrders();renderCustomers();renderRecent();loadSettings();loadSEO()}
function renderStats(){document.getElementById("productsCount").textContent=products.length;document.getElementById("ordersCount").textContent=orders.length;document.getElementById("cartCount").textContent=JSON.parse(localStorage.getItem("meknesCart")||"[]").reduce((a,x)=>a+x.qty,0);document.getElementById("sales").textContent=orders.filter(o=>o.status!=="ملغى").reduce((a,o)=>a+o.total,0)+" DH"}
const catName={olives:"الزيتون",oil:"زيت الزيتون",pepper:"الفلفل",traditional:"تراثي"};
function renderProducts(){document.getElementById("productsTable").innerHTML=products.map(p=>`<tr><td><b>${p.name}</b><br><small>${p.fr}</small></td><td>${catName[p.cat]||p.cat}</td><td>${p.price} DH</td><td>${p.stock}</td><td><span class="pill">${p.stock>0?"نشط":"نفد"}</span></td><td class="actionsCell"><button onclick="editProduct(${p.id})">تعديل</button><button onclick="deleteProduct(${p.id})">حذف</button></td></tr>`).join("")}
function openProduct(){document.getElementById("pid").value="";["pname","pfr","pprice","pimg","pdesc"].forEach(id=>document.getElementById(id).value="");document.getElementById("punit").value="500g";document.getElementById("pstock").value=20;document.getElementById("productModal").classList.add("show")}
function closeProduct(){document.getElementById("productModal").classList.remove("show")}
function editProduct(id){let p=products.find(x=>x.id===id);document.getElementById("pid").value=p.id;document.getElementById("pname").value=p.name;document.getElementById("pfr").value=p.fr;document.getElementById("pcat").value=p.cat;document.getElementById("pprice").value=p.price;document.getElementById("punit").value=p.unit;document.getElementById("pstock").value=p.stock;document.getElementById("pimg").value=p.img;document.getElementById("pdesc").value=p.desc;document.getElementById("productModal").classList.add("show")}
function saveProduct(){let id=+document.getElementById("pid").value||Date.now();let p={id,name:document.getElementById("pname").value,fr:document.getElementById("pfr").value,cat:document.getElementById("pcat").value,price:+document.getElementById("pprice").value,unit:document.getElementById("punit").value,stock:+document.getElementById("pstock").value,img:document.getElementById("pimg").value,desc:document.getElementById("pdesc").value};let i=products.findIndex(x=>x.id===id);i>-1?products[i]=p:products.push(p);saveAll();closeProduct();renderAll()}
function deleteProduct(id){if(confirm("حذف هذا المنتج؟")){products=products.filter(p=>p.id!==id);saveAll();renderAll()}}
function renderOrders(){document.getElementById("ordersTable").innerHTML=orders.length?orders.map(o=>`<tr><td><b>#${o.id.toString().slice(-6)}</b></td><td>${o.name}<br><small>${o.phone}</small></td><td>${o.city}</td><td>${o.total} DH</td><td><select onchange="status(${o.id},this.value)"><option ${o.status==="جديد"?"selected":""}>جديد</option><option ${o.status==="قيد التجهيز"?"selected":""}>قيد التجهيز</option><option ${o.status==="تم الشحن"?"selected":""}>تم الشحن</option><option ${o.status==="مكتمل"?"selected":""}>مكتمل</option><option ${o.status==="ملغى"?"selected":""}>ملغى</option></select></td><td>${o.date}</td><td><button class="actionsCell" onclick="deleteOrder(${o.id})">حذف</button></td></tr>`).join(""):`<tr><td colspan="7">لا توجد طلبات بعد.</td></tr>`}
function status(id,v){let o=orders.find(x=>x.id===id);if(o)o.status=v;saveAll();renderAll()}
function deleteOrder(id){if(confirm("حذف الطلب؟")){orders=orders.filter(x=>x.id!==id);saveAll();renderAll()}}
function seedOrder(){orders.unshift({id:Date.now(),name:"زبون تجريبي",phone:"0600000000",city:"مكناس",total:120,status:"جديد",date:new Date().toLocaleDateString("fr-MA")});saveAll();renderAll()}
function renderRecent(){document.getElementById("recentOrders").innerHTML=orders.slice(0,5).map(o=>`<div style="display:flex;justify-content:space-between;border-bottom:1px solid #edf1ed;padding:12px 0;font-size:10px"><span>#${o.id.toString().slice(-6)} — ${o.name}</span><b>${o.total} DH</b></div>`).join("")||"<p style='color:#8a958e;font-size:11px'>لا توجد طلبات.</p>"}
function renderCustomers(){let map={};orders.forEach(o=>{let k=o.phone||o.name;map[k]??={name:o.name,phone:o.phone,city:o.city,count:0,total:0};map[k].count++;map[k].total+=o.total});document.getElementById("customersTable").innerHTML=Object.values(map).map(c=>`<tr><td><b>${c.name}</b></td><td>${c.phone}</td><td>${c.city}</td><td>${c.count}</td><td>${c.total} DH</td></tr>`).join("")||"<tr><td colspan='5'>لا يوجد زبناء بعد.</td></tr>"}
function saveSettings(){settings={shopName:shopName.value,whatsapp:whatsapp.value,instagram:instagram.value,city:city.value,orderPrefix:orderPrefix.value};localStorage.setItem(SKEY,JSON.stringify(settings));alert("تم الحفظ")}
function loadSettings(){if(!settings.shopName)return;shopName.value=settings.shopName;whatsapp.value=settings.whatsapp;instagram.value=settings.instagram;city.value=settings.city;orderPrefix.value=settings.orderPrefix}
function saveSEO(){let seo={title:seoTitle.value,desc:seoDesc.value,titleFr:seoTitleFr.value,descFr:seoDescFr.value,keywords:keywords.value,trust:trustText.value};localStorage.setItem(SEO,JSON.stringify(seo));alert("تم حفظ إعدادات SEO")}
function loadSEO(){let s=JSON.parse(localStorage.getItem(SEO)||"null");if(!s)return;seoTitle.value=s.title;seoDesc.value=s.desc;seoTitleFr.value=s.titleFr;seoDescFr.value=s.descFr;keywords.value=s.keywords;trustText.value=s.trust}
